### ISSUE TITLE
Safari - Infinite Scrollbar has artifact 

### ISSUE THREAD

**Issue by vonsichart200** [predix-ui/predix-ui.github.io#231] opened 2017-08-03 20:57 UTC
Infinite Scrollbar has artifact/blue piece missing on the right side when blue element reduces size.
![2xb24yw7ur8hhcdgcdofd4xc4ubgbjytt7clrcuuaaaaasuvork5cyii](https://user-images.githubusercontent.com/25111262/28943422-a4ee7484-7853-11e7-8347-deb88267e9d0.png)

**Comment by randyaskin** [comment] 2017-08-03 21:03
Duplicate of #223 , #183, and https://github.com/PredixDev/px-progress-bar/issues/3

**Closed as completed by randyaskin** 2017-08-03 21:03 UTC
Labels: duplicate
