### ISSUE TITLE
FF: "Edit" button in timeseries doesn't fit in propsContainer div (FF only).

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#27] opened 2017-01-31 20:34 UTC
This seems to be a FF special. (Version: 51)

In timeseries demo page, the Edit button doesn't fit in the properties div.

Screenshot:

![screen shot 2017-01-31 at 12 25 13 pm](https://cloud.githubusercontent.com/assets/10835611/22483311/857d0738-e7b1-11e6-8c11-f144b736bfa1.png)

**Comment by davidrleonard** [comment] 2017-08-03 20:41
Can't reproduce. Think we can close this one, as it seems to have been fixed since it was reported.

**Closed as completed by davidrleonard** 2017-08-03 20:41 UTC
Labels: browser bug
