### ISSUE TITLE
Progress bar:  the animation looks jittery in Safari9 at the end of the bar.

### ISSUE THREAD

**Issue by ppeyro** [predix-ui/predix-ui.github.io#223] opened 2017-08-02 23:40 UTC
This is only in Safari9 and when the progress bar hits the end of the bar and returns to refill the bar.
No specific errors in the log.

## Screenshot:

![screen shot 2017-08-02 at 4 37 45 pm](https://user-images.githubusercontent.com/10835611/28899648-23481dde-77a1-11e7-9e02-d4a6a73fe64f.png)

**Comment by randyaskin** [comment] 2017-08-03 16:36
Duplicate of #183 and https://github.com/PredixDev/px-progress-bar/issues/3

**Closed as completed by randyaskin** 2017-08-03 16:36 UTC
Labels: duplicate, p2
